### PR TITLE
PyInstaller distributions

### PR DESCRIPTION
**Pull request by corranwebster**
Draft PR that is starting work on distribution using PyInstaller.  When done, this will consist of:

- [x] discussion of PyInstaller that can be raided to produce slides
- [x] sample hook files for core ETS libraries (untested)
- [ ] sample `.spec` file
- [ ] basic example that bundles a "hello world" TraitsUI app
- [ ] exercise to set up a `.spec` file for an application and create and app

### CODE REVIEW

**Comment by jonathanrocher** [comment]
Hey @corranwebster : do you have time to push this over the hump soon-ish so we can get this tested and in?

**Comment by jonathanrocher** [comment]
Guys, OK with merging this to share what's here with attendees?

**Review by chamshop — APPROVED** [review]
Just a couple comments.

**Comment by jonathanrocher** [comment]
Thanks @chamshop !

**Pull request merged**
