### PR TITLE
Feature: add stage 8 setuptools

### PR DESCRIPTION
**Pull request by jonathanrocher**
Simply adds a fuller `setup.py` file which collects all data files and adds a command line entry point. Simplify all other setup.py files so they are as simple as possible.

### CODE REVIEW

**Comment by jonathanrocher** [comment]
cc @siddhantwahal @prabhuramachandran

**Review by siddhantwahal — CHANGES_REQUESTED** [review]
This is still using the old models. Need more time to take a detailed look...

**Review by siddhantwahal — APPROVED** [review]
Thanks!

**Comment by jonathanrocher** [comment]
Thanks for the review @siddhantwahal and catching the inconsistent models!

**Pull request merged**
